version: '3'
services:
  online-cinema.api:
    image: ghcr.io/itsaln/youtube2.0-api/youtube2.0:develop
    container_name: youtube2.0
    restart: always
    ports:
      - 5000:5000
    volumes:
      - ./.env:/opt/app/.env